services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile.elt
    ports:
      - "3000:3000"
    environment:
      - DUCKDB_PATH=/mnt/data/warehouse.duckdb
    volumes:
      - dagster-home:/mnt/dagster_home
      - ./.dbt:/mnt/.dbt
      - ./data:/mnt/data

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.serve
    ports:
      - "8501:8501"
    environment:
      - DUCKDB_PATH=/mnt/data/warehouse.duckdb
    volumes:
      - ./data:/mnt/data

volumes:
  dagster-home: